[ICU-2161] obsolete
X-SVN-Rev: 11258

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1087,7 +1087,7 @@ if test "$srcdir" = "."; then
   fi
 fi
 
-ac_config_files="$ac_config_files icuapps.mk Makefile usort/Makefile usort/lib/Makefile usort/client/Makefile locexp/Makefile locexp/tools/Makefile locexp/util/Makefile locexp/resource/Makefile ubrowse/Makefile dumpdat/Makefile xlitomatic/Makefile rtfcvrt/Makefile XMLConverter/Makefile"
+ac_config_files="$ac_config_files icuapps.mk Makefile usort/Makefile usort/lib/Makefile usort/client/Makefile locexp/Makefile locexp/tools/Makefile locexp/util/Makefile locexp/resource/Makefile ubrowse/Makefile dumpdat/Makefile xlitomatic/Makefile rtfcvrt/Makefile XMLConverter/Makefile nbrowser/Makefile obsolete/Makefile test/Makefile test/testdata/Makefile test/obstest/Makefile"
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
 # tests run on this system so they can be shared between configure
@@ -1433,7 +1433,12 @@ do
   "xlitomatic/Makefile" ) CONFIG_FILES="$CONFIG_FILES xlitomatic/Makefile" ;;
   "rtfcvrt/Makefile" ) CONFIG_FILES="$CONFIG_FILES rtfcvrt/Makefile" ;;
   "XMLConverter/Makefile" ) CONFIG_FILES="$CONFIG_FILES XMLConverter/Makefile" ;;
-  *) { { echo "$as_me:1436: error: invalid argument: $ac_config_target" >&5
+  "nbrowser/Makefile" ) CONFIG_FILES="$CONFIG_FILES nbrowser/Makefile" ;;
+  "obsolete/Makefile" ) CONFIG_FILES="$CONFIG_FILES obsolete/Makefile" ;;
+  "test/Makefile" ) CONFIG_FILES="$CONFIG_FILES test/Makefile" ;;
+  "test/testdata/Makefile" ) CONFIG_FILES="$CONFIG_FILES test/testdata/Makefile" ;;
+  "test/obstest/Makefile" ) CONFIG_FILES="$CONFIG_FILES test/obstest/Makefile" ;;
+  *) { { echo "$as_me:1441: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -1633,7 +1638,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:1636: creating $ac_file" >&5
+    { echo "$as_me:1641: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -1651,7 +1656,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:1654: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:1659: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -1664,7 +1669,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:1667: error: cannot find input file: $f" >&5
+           { { echo "$as_me:1672: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
